name: order-processing-system

services:
  auth-db:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME:-auth_db}
      POSTGRES_USER: ${AUTH_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-auth_password}
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTH_DB_USERNAME:-postgres} -d ${AUTH_DB_NAME:-auth_db}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME:-order_db}
      POSTGRES_USER: ${ORDER_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD:-order_password}
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${ORDER_DB_USERNAME:-postgres} -d ${ORDER_DB_NAME:-order_db}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  inventory-db:
    image: postgres:17
    container_name: inventory-db
    environment:
      POSTGRES_DB: ${INVENTORY_DB_NAME:-inventory_db}
      POSTGRES_USER: ${INVENTORY_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASSWORD:-inventory_password}
    ports:
      - "5435:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${INVENTORY_DB_USERNAME:-postgres} -d ${INVENTORY_DB_NAME:-inventory_db}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"
        ]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 20s
    restart: unless-stopped

volumes:
  auth-db-data:
  order-db-data:
  inventory-db-data:
  kafka-data: