spring:
  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${AUTH_DB_USERNAME:postgres}
    password: ${AUTH_DB_PASSWORD:auth_password}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
  
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  password-reset:
    expiration-minutes: ${PASSWORD_RESET_EXPIRATION_MINUTES:15}
    frontend-url: ${FRONTEND_URL:http://localhost:5173}
    from-email: ${MAIL_FROM:no-reply@orderflow.local}
  kafka:
    topics:
      user-security-version-changed: user.security-version.changed.v1
  